ARG HTCGRID_ACCOUNT 
ARG HTCGRID_REGION
FROM ${HTCGRID_ACCOUNT}.dkr.ecr.${HTCGRID_REGION}.amazonaws.com/ecr-public/lambda/python:3.8
RUN yum install -d1 -y  zip

RUN mkdir -p /app
WORKDIR /app
COPY portfolio_pricing_engine.py .
COPY american_options.py .
COPY european_options.py .
COPY ql_common.py .
RUN pip install --target=/app QuantLib
RUN mkdir -p /app/build
RUN zip -yr lambda.zip .
ENTRYPOINT cp lambda.zip /app/build


