# ---
# apiVersion: keda.sh/v1alpha1
# kind: TriggerAuthentication
# metadata:
#   name: htc-agent-scaler-auth
# spec:
#   podIdentity:
#     provider: aws-eks # Use aws-eks when using IRSA
# ---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "agent-htc-lambda.fullname" . }}-scaling-metrics
spec:
  scaleTargetRef:
    name: {{ include "agent-htc-lambda.fullname" . }}
  minReplicaCount: {{ .Values.hpa.minAgent }}
  maxReplicaCount: {{ .Values.hpa.maxAgent }}
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: {{ .Values.hpa.queueURL | quote }}
        queueLength: {{ .Values.hpa.metric.targetValue | quote }}
        awsRegion: {{ .Values.hpa.metric.region }}
        identityOwner: operator
