{
 "title": "HTC Dashboard - Filterable",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pod_id",
    "label": "Pod ID",
    "query": "SELECT DISTINCT(\"str_pod_id\") FROM \"agent_post\""
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Submitted Tasks by Clients (per second)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "submit_tasks",
     "select": [
      [
       { "params": [ "count_submitted_tasks" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Task Completion Rate (per second)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "query": "SELECT sum(\"ddb_set_task_finished_succeeded\")  / 10 FROM /^$pod_id$/ WHERE $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       {
        "params": [
         "ddb_set_task_finished_succeeded"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "str_pod_id::field", "operator": "=~", "value": "/^$pod_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Running Tasks (Estimated)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Running Tasks",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "submit_tasks",
     "select": [
      [
       { "params": [ "count_submitted_tasks" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "query": "SELECT sum(\"ddb_set_task_finished_succeeded\") * -1 FROM \"agent_post\" WHERE $timeFilter AND (\"str_pod_id\" = '$pod_id' OR '$pod_id' = 'All') GROUP BY time(10s) fill(null)",
     "select": [
      [
       {
        "params": [
         "ddb_set_task_finished_succeeded"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " * -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "str_pod_id::field", "operator": "=~", "value": "/^$pod_id$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ttl_checker",
     "select": [
      [
       { "params": [ "counter_expired_tasks" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " * -1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Agent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Agent-Pre Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Failed to Acquired Task DDB",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_pre",
     "select": [
      [
       { "params": [ "agent_failed_to_claim_ddb_task" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "No Messages In SQS events",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_pre",
     "select": [
      [
       {
        "params": [
         "agent_no_messages_in_tasks_queue"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Succesfully Acquired Task DDB",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_pre",
     "select": [
      [
       {
        "params": [
         "agent_successful_acquire_a_task"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Agent's Count",
   "type": "graph",
   "description": "Count of Agent's that have finished at least one task within last minute. When queue is full, this number should be equal to the total number of pods in the system",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "alias": "Active Agents",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "str_pod_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Agent Job Exec Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "query": "SELECT mean(\"task_exec_time_ms\") FROM \"agent_post\" WHERE $timeFilter AND \"task_id\" =~ /^$task_id$/ GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "task_exec_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Agent Job Exec Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "alias": "50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "task_exec_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    },
    {
     "alias": "95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "task_exec_time_ms" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Agent Total Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "alias": "Total Agent Time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "agent_total_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Agent Total Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "alias": "50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "agent_total_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    },
    {
     "alias": "95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "agent_total_time_ms" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TTL Lambda",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "TTL Lambda",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ttl_checker",
     "select": [
      [
       { "params": [ "counter_expired_tasks" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ttl_checker",
     "select": [
      [
       { "params": [ "counter_failed_tasks" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ttl_checker",
     "select": [
      [
       { "params": [ "counter_inconsistent_state" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ttl_checker",
     "select": [
      [
       { "params": [ "counter_released_tasks" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Influx API Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Measurements Received/sec",
     "type": "graph",
     "gridPos": { "h": 16, "w": 10, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "submit tasks",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "submit_tasks",
       "select": [
        [
         { "params": [ "task_construction_ms" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ " / 10" ], "type": "math" }
        ]
       ]
      },
      {
       "alias": "get results",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "get_results",
       "select": [
        [
         { "params": [ "get_results_invocation_time" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ " / 10" ], "type": "math" }
        ]
       ]
      },
      {
       "alias": "TTL",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ttl_checker",
       "select": [
        [
         { "params": [ "ttl_execution_time" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ " / 10" ], "type": "math" }
        ]
       ]
      },
      {
       "alias": "Agent PRE",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "agent_pre",
       "select": [
        [
         { "params": [ "sqs_queuing_time_ms" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ " / 10" ], "type": "math" }
        ]
       ]
      },
      {
       "alias": "Agent POST",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "agent_post",
       "select": [
        [
         { "params": [ "agent_total_time_ms" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ " / 10" ], "type": "math" }
        ]
       ]
      }
     ]
    },
    {
     "title": "From Pre-Agent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 10, "y": 45 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "95th",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "agent_pre",
       "select": [
        [
         { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "agent_pre",
       "select": [
        [
         { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      },
      {
       "alias": "50th",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "agent_pre",
       "select": [
        [
         { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
         { "params": [ "50" ], "type": "percentile" }
        ]
       ]
      }
     ]
    },
    {
     "title": "From Post Agent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "95th",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "agent_post",
       "select": [
        [
         { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "agent_post",
       "select": [
        [
         { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      },
      {
       "alias": "50th",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "agent_post",
       "select": [
        [
         { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
         { "params": [ "50" ], "type": "percentile" }
        ]
       ]
      }
     ]
    },
    {
     "title": "From Submit Tasks Lambda",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 53 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "95th",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "submit_tasks",
       "select": [
        [
         { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "submit_tasks",
       "select": [
        [
         { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "From Get Results",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 15, "y": 53 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "95th",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "get_results",
       "select": [
        [
         { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "get_results",
       "select": [
        [
         { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "From TTL Lambda",
     "type": "graph",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 53 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "95th",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "ttl_checker",
       "select": [
        [
         { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "ttl_checker",
       "select": [
        [
         { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Task Completion Rate/5min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       {
        "params": [
         "ddb_set_task_finished_succeeded"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "str_pod_id::field", "operator": "=~", "value": "/^$pod_id$/" }
     ]
    }
   ]
  }
 ]
}