{
 "title": "HTC Global View",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Client Submitted Tasks (per second)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "submit_tasks",
     "select": [
      [
       { "params": [ "count_submitted_tasks" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Task Completion Rate/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       {
        "params": [
         "ddb_set_task_finished_succeeded"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "Congestion Control (CC)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "DDB Acquire Task Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "50th",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_pre",
     "query": "SELECT percentile(\"ddb_task_claiming_time_ms\", 50), percentile(\"ddb_task_claiming_time_ms\", 99), percentile(\"ddb_task_claiming_time_ms\", 95) FROM \"agent_pre\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ddb_task_claiming_time_ms" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" }
      ]
     ]
    },
    {
     "alias": "95th",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_pre",
     "query": "SELECT percentile(\"ddb_task_claiming_time_ms\", 50), percentile(\"ddb_task_claiming_time_ms\", 99), percentile(\"ddb_task_claiming_time_ms\", 95) FROM \"agent_pre\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ddb_task_claiming_time_ms" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_pre",
     "query": "SELECT percentile(\"ddb_task_claiming_time_ms\", 50), percentile(\"ddb_task_claiming_time_ms\", 99), percentile(\"ddb_task_claiming_time_ms\", 95) FROM \"agent_pre\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ddb_task_claiming_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CC Time Since Last Decrease",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "50th",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "query": "SELECT percentile(\"ddb_task_claiming_time_ms\", 50), percentile(\"ddb_task_claiming_time_ms\", 99), percentile(\"ddb_task_claiming_time_ms\", 95) FROM \"agent_pre\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rc_time_since_last_decrease" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" }
      ]
     ]
    },
    {
     "alias": "99th",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "query": "SELECT percentile(\"ddb_task_claiming_time_ms\", 50), percentile(\"ddb_task_claiming_time_ms\", 99), percentile(\"ddb_task_claiming_time_ms\", 95) FROM \"agent_pre\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rc_time_since_last_decrease" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "query": "SELECT percentile(\"ddb_task_claiming_time_ms\", 50), percentile(\"ddb_task_claiming_time_ms\", 99), percentile(\"ddb_task_claiming_time_ms\", 95) FROM \"agent_pre\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rc_time_since_last_decrease" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CC Agent's Achieved Rates",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "10th",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "rc_current_achieved_rate" ], "type": "field" },
       { "params": [ "10" ], "type": "percentile" }
      ]
     ]
    },
    {
     "alias": "50th",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "rc_current_achieved_rate" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" }
      ]
     ]
    },
    {
     "alias": "95th",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "rc_current_achieved_rate" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ]
     ]
    },
    {
     "alias": "99th",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "rc_current_achieved_rate" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CC Agent's Allowed Rates",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 10, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "10th",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "rc_current_allowed_rate" ], "type": "field" },
       { "params": [ "10" ], "type": "percentile" }
      ]
     ]
    },
    {
     "alias": "50th",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "rc_current_allowed_rate" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" }
      ]
     ]
    },
    {
     "alias": "95th",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "rc_current_allowed_rate" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ]
     ]
    },
    {
     "alias": "99th",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "rc_current_allowed_rate" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CC Agent's MAX Achieved Rates",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "10th",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "rc_max_achieved_rate" ], "type": "field" },
       { "params": [ "10" ], "type": "percentile" }
      ]
     ]
    },
    {
     "alias": "50th",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "rc_max_achieved_rate" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" }
      ]
     ]
    },
    {
     "alias": "95th",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "rc_max_achieved_rate" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ]
     ]
    },
    {
     "alias": "99th",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "rc_max_achieved_rate" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CC Congestion Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Count",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "agent_pre",
     "query": "SELECT percentile(\"ddb_task_claiming_time_ms\", 50), percentile(\"ddb_task_claiming_time_ms\", 99), percentile(\"ddb_task_claiming_time_ms\", 95) FROM \"agent_pre\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rc_cubic_decrease_event" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Agent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Agent-Pre Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Failed to Acquired Task DDB",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_pre",
     "select": [
      [
       { "params": [ "agent_failed_to_claim_ddb_task" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "No Messages In SQS events",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_pre",
     "select": [
      [
       {
        "params": [
         "agent_no_messages_in_tasks_queue"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Succesfully Acquired Task DDB",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_pre",
     "select": [
      [
       {
        "params": [
         "agent_successful_acquire_a_task"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Agent's Count",
   "type": "graph",
   "description": "Count of Agent's that have finished at least one task within last minute. When queue is full, this number should be equal to the total number of pods in the system",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Active Agents",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "str_pod_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Agent Job Exec Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "query": "SELECT mean(\"task_exec_time_ms\") FROM \"agent_post\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "task_exec_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Agent Job Exec Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "task_exec_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    },
    {
     "alias": "95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "task_exec_time_ms" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Agent Total Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total Agent Time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "agent_total_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Agent Total Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "50th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "agent_total_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    },
    {
     "alias": "95th",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "agent_total_time_ms" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TTL Lambda",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true
  },
  {
   "title": "TTL Lambda",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ttl_checker",
     "select": [
      [
       { "params": [ "counter_expired_tasks" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ttl_checker",
     "select": [
      [
       { "params": [ "counter_failed_tasks" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ttl_checker",
     "select": [
      [
       { "params": [ "counter_inconsistent_state" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ttl_checker",
     "select": [
      [
       { "params": [ "counter_released_tasks" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Influx API Meatrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Measurements Received/sec",
   "type": "graph",
   "gridPos": { "h": 16, "w": 10, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "submit tasks",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "submit_tasks",
     "select": [
      [
       { "params": [ "task_construction_ms" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "get results",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "get_results",
     "select": [
      [
       { "params": [ "get_results_invocation_time" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "TTL",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ttl_checker",
     "select": [
      [
       { "params": [ "ttl_execution_time" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Agent PRE",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_pre",
     "select": [
      [
       { "params": [ "sqs_queuing_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Agent POST",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "agent_total_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "From Pre-Agent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 72 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "95th",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "agent_pre",
     "select": [
      [
       { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "agent_pre",
     "select": [
      [
       { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "50th",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "agent_pre",
     "select": [
      [
       { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  {
   "title": "From Post Agent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "95th",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "50th",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "agent_post",
     "select": [
      [
       { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  {
   "title": "From Submit Tasks Lambda",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 80 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "95th",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "submit_tasks",
     "select": [
      [
       { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "submit_tasks",
     "select": [
      [
       { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "From Get Results",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 80 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "95th",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "get_results",
     "select": [
      [
       { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "get_results",
     "select": [
      [
       { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "From TTL Lambda",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 80 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "95th",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ttl_checker",
     "select": [
      [
       { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ttl_checker",
     "select": [
      [
       { "params": [ "last_batch_submission_delay_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}