# Copyright 2024 Amazon.com, Inc. or its affiliates. 
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 https://aws.amazon.com/apache-2-0/

awsRegion: "${region}"

autoDiscovery:
  clusterName: "${cluster_name}"
extraArgs:
  logtostderr: true
  stderrthreshold: info
  v: 4
  aws-use-static-instance-list: true

extraEnv:
  AWS_STS_REGIONAL_ENDPOINTS: "regional"

resources:
  limits:
    cpu: 3000m
    memory: 3000Mi
  requests:
    cpu: 1000m
    memory: 1000Mi

image:
  repository: "${aws_htc_ecr}/registry-k8s-io/autoscaling/cluster-autoscaler"
  tag: "${k8s_ca_version}"

nodeSelector:
  htc/node-type: "core"

tolerations:
  - key: "htc/node-type"
    operator: "Equal"
    value: "core"
    effect: "NoSchedule"
