# Copyright 2023 Amazon.com, Inc. or its affiliates. 
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 https://aws.amazon.com/apache-2-0/

quiet: false

format: sarif

scan:
  scanners:
    - vuln
    - misconfig
    # - secret
    # - license

  skip-dirs:
    - '**/.terraform'
    - venv/

# misconfiguration:
#   terraform:
#     exclude-downloaded-modules: true

# These flag dont seem to be working from the config file.

# severity:
#   - MEDIUM
#   - HIGH
#   - CRITICAL
#   - UNKNOWN

vulnerability:
  ignore-unfixed: true
