#Builder Container
ARG HTCGRID_ECR_REPO
FROM ${HTCGRID_ECR_REPO}/ecr-public/docker/library/python:3.8-slim

# Run as user nobody:nogroup
ARG USER=65534 #nobody
ARG GROUP=65534 #nogroup

RUN apt-get update && \
    apt-get install -y \
      --no-install-recommends \
      binutils \
      procps \
      gcc && \
    pip install --no-cache-dir setuptools==45.0.0 pyinstaller && \
    mkdir -p /dist /app/agent

COPY ./dist/* /dist/
COPY ./source/compute_plane/python/agent/requirements.txt ./source/compute_plane/python/agent/agent.py /app/agent/

WORKDIR /app/agent
RUN pip install --no-cache-dir -r requirements.txt && \
    pyinstaller --hidden-import=pkg_resources.py2_warn -F agent.py && \
    cp ./dist/agent ./agent && \
    chown -R $USER:$GROUP /app

USER ${USER}:${GROUP}

################################################################################

# Main Container
ARG HTCGRID_ECR_REPO
FROM ${HTCGRID_ECR_REPO}/ecr-public/docker/library/python:3.8-slim

# Run as user nobody:nogroup
ARG USER=65534 #nobody
ARG GROUP=65534 #nogroup

RUN apt-get update && \
    apt-get install -y \
      --no-install-recommends \
      build-essential \
      procps && \
      mkdir -p /app
 
COPY /examples/workloads/c++/mock_computation/mock_compute_engine.cpp ./examples/workloads/c++/mock_computation/Makefile /app/
RUN make && \
    chown -R $USER:$GROUP /app
COPY --from=0 /app/agent /app/agent

USER ${USER}:${GROUP}

WORKDIR /app
ENTRYPOINT ["python" , "./agent.py"]
