ARG HTCGRID_ECR_REPO
FROM ${HTCGRID_ECR_REPO}/ecr-public/docker/library/python:3.8-slim

# Run as user nobody:nogroup
ARG USER=65534 #nobody
ARG GROUP=65534 #nogroup

RUN apt-get update && \
    apt-get install -y \
      --no-install-recommends \
      binutils \
      procps \
      gcc && \
    mkdir -p /dist /app/agent

COPY ./dist/* /dist/
COPY ./source/compute_plane/python/agent/requirements.txt ./source/compute_plane/python/agent/agent.py /app/agent/

WORKDIR /app/agent
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    chown -R $USER:$GROUP /app /dist

USER ${USER}:${GROUP}

ENTRYPOINT [ "python" , "./agent.py"]
