---
# Copyright 2023 Amazon.com, Inc. and its affiliates. All Rights Reserved.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#                 http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.nse.

AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy the necessary resources for storing the state of a grid'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: 'Tag needs to follow S3 naming rules.'
        Parameters:
          - BucketTag
Parameters:
  BucketTag:
    Description: 'Recommended to prefix the different required buckets'
    Type: String
    Default: ''
Resources:
  LambdaUnitHtcGrid:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub
        - '${BucketTag}-lambda-unit-htc-grid-${RANDOM}'
        - RANDOM: !Select [0, !Split ['-', !Select [2, !Split ['/', !Ref 'AWS::StackId' ]]]]
    DeletionPolicy: Delete
Outputs:
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
  LambdaUnitHtcGridBucketId:
    Description: 'S3 bucket name of lambda unit htc-grid'
    Value: !Ref LambdaUnitHtcGrid