FROM public.ecr.aws/lambda/python:3.8
RUN yum install -d1 -y  zip
RUN mkdir -p /app
WORKDIR /app
COPY mock_compute_engine.py .
RUN mkdir -p /app/build
RUN zip -9yr lambda.zip .
ENTRYPOINT cp lambda.zip /app/build


