ARG HTCGRID_ECR_REPO
FROM ${HTCGRID_ECR_REPO}/ecr-public/lambda/python:3.8

# Run as user nobody:nobody
ARG USER=99 #nobody
ARG GROUP=99 #nobody

RUN yum update -y && \
    yum install -y \
      zip && \
    yum clean all && \
    rm -rf /var/cache/yum && \
    mkdir -p /app/build && \
    chown -R $USER:$GROUP /app

USER ${USER}:${GROUP}

WORKDIR /app
COPY mock_compute_engine.py /app/

RUN zip -9yr lambda.zip .

ENTRYPOINT ["cp", "lambda.zip", "/app/build" ]
