ARG HTCGRID_ACCOUNT
ARG HTCGRID_REGION
FROM ${HTCGRID_ACCOUNT}.dkr.ecr.${HTCGRID_REGION}.amazonaws.com/ecr-public/lambda/java:17

# COPY my-app/target/classes ${LAMBDA_TASK_ROOT}
# COPY my-app/target/dependency/* ${LAMBDA_TASK_ROOT}/lib/
# RUN mkdir -p ${LAMBDA_TASK_ROOT}/KBG_ECR

COPY lambda_entry_point.sh  /lambda_entrypoint_signal.sh
RUN chmod u+x /lambda_entrypoint_signal.sh
ENTRYPOINT ["/lambda_entrypoint_signal.sh"]